### ISSUE TITLE
Do you have pretrained model weights?

### ISSUE THREAD

**Issue by ogencoglu** [gritzner/SegForestNet#2]
Do you have pretrained model weights for the segmentation model or an ONNX version?

**Comment by gritzner** [comment]
Sorry for the late reply, I'm currently out of office. I will have a look whether I still have the trained model weights next week. However, due to important appointments I have early next week, I will not be able to look for the weights and upload them to a file share, if I still have them, before the end of next week. Also, they will not be ONNX versions but rather PyTorch state_dicts.

**Comment by ogencoglu** [comment]
Thanks for the swift reply. I understand and appreciate. state_dicts are OK as long as I can load the model definition somehow to run inference on arbitrary images. I can myself quantize and convert to ONNX to profile the latency.

**Comment by gritzner** [comment]
I just created a release here on GitHub and attached the model weights to that release. You can find the release on the right-hand side of the repository's main page.
